name: 'PR Merge Bot'
description: 'Merge pull requests when certain conditions are met'
branding:
  icon: 'git-merge'
  color: 'purple'
inputs:
  test:
    description: 'Runs in test mode and will comment rather than merge'
    required: false
    default: false
  labels:
    description: 'Labels required for integration'
    required: true
    default: 'ready'
  blocking-labels:
    description: 'Labels that block the integration'
    required: false
    default: 'do not merge'
  reviewers:
    description: 'Reviewers required and reviewers must all approve'
    required: false
    default: true
  checks_enabled:
    description: 'All checks must be completed to be eligible to integrate'
    required: false
    default: true
  method:
    description: 'Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is `merge`.'
    required: false
    default: 'merge'
runs:
  using: 'node12'
  main: 'index.js'
