name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - review_request_removed
      - review_requested
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted
  status:

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: false
        reviewers: false
        labels: ready
        blocking-labels: do not merge
        method: squash
